name: frp
on:
  repository_dispatch:
  workflow_dispatch:
jobs:
  frp:
    runs-on: ubuntu-latest
    steps:
      - name: A Debugger Tool For Github Actions
        uses: HalfCoke/gitactions-debugger@v1
        timeout-minutes: 30
        continue-on-error: true
        with:
          frp_server_addr: ${{ secrets.FRP_SERVER_ADDR }}
          frp_server_port: ${{ secrets.FRP_SERVER_PORT }}
          frp_token: ${{ secrets.FRP_TOKEN }}
          ssh_port: ${{ secrets.SSH_PORT }}
          timeout: 30